Repository MystenLabs/walrus, pull requests merged in 2025-04, with the labels that each got.

#1811 feat: Modify orchestrator to deploy clients
  .gitignore
  Cargo.lock
  crates/walrus-e2e-tests/tests/test_client.rs
  crates/walrus-orchestrator/Cargo.toml
  crates/walrus-orchestrator/assets/dashboard-template.json
  crates/walrus-orchestrator/src/benchmark.rs
  crates/walrus-orchestrator/src/client.rs
  crates/walrus-orchestrator/src/client/aws.rs
  crates/walrus-orchestrator/src/logs.rs
  crates/walrus-orchestrator/src/main.rs
  crates/walrus-orchestrator/src/measurements.rs
  crates/walrus-orchestrator/src/monitor.rs
  crates/walrus-orchestrator/src/orchestrator.rs
  crates/walrus-orchestrator/src/protocol.rs
  crates/walrus-orchestrator/src/protocol/target.rs
  crates/walrus-orchestrator/src/settings.rs
  crates/walrus-orchestrator/src/ssh.rs
  crates/walrus-service/src/client.rs
  crates/walrus-service/src/client/daemon.rs
  crates/walrus-service/src/client/metrics.rs
  crates/walrus-simtest/src/test_utils.rs
  crates/walrus-stress/src/generator.rs
  crates/walrus-stress/src/generator/write_client.rs
  crates/walrus-stress/src/main.rs
Labels: deployment

#1942 docs: extend SDKs page
  docs/book/usage/sdks.md
Labels: documentation

#1950 docs: add info on epoch duration and overview over network parameters
  docs/book/design/architecture.md
  docs/book/glossary.md
  docs/book/usage/client-cli.md
  docs/book/usage/networks.md
Labels: documentation

#1956 docs: add whitepaper v2
  docs/book/walrus.pdf
  docs/book/walrus_whitepaper_v1.pdf
  docs/book/walrus_whitepaper_v2.pdf
Labels: documentation

#1943 fix(client): fixed generation of a new wallet at default path
  crates/walrus-service/src/client/cli/args.rs
  crates/walrus-service/src/client/cli/runner.rs
  docs/book/usage/networks.md
  docs/book/usage/setup.md
Labels: documentation, client

#2011 docs: clean up links in old blog posts
  book.toml
  docs/book/blog/00_intro.md
  docs/book/blog/01_announcing_walrus.md
  docs/book/blog/02_devnet_update.md
  docs/book/blog/03_whitepaper.md
  docs/book/blog/04_testnet_update.md
  docs/book/blog/05_testnet_redeployment.md
Labels: documentation
